- README.md
- index.js
- package.json
Sets the existing ruleset of `stripes-components` as the new baseline for `eslint-config-stripes`.
> Import existing stripes components lint configs

- index.js
Based on conversation here: https://github.com/folio-org/stripes-core/pull/42
These few rules felt overly restrictive:
- `no-else-return`: the explicit `else` `return` can be much easier to read and parse as a human, even if it's a tiny bit more code for a machine
- `no-nested-ternary`: having it on forces jsx logic to be simpler, but can be very unwieldy
- `no-plusplus`: ++
> Turn off a few default rules

- index.js
Following this rule introduces syntactic clutter that does not always improve, and sometimes impedes, clarity.
For example, I just moved the `<SearchAndSort>` component from ui-users (which still has its own ESLint config) to stripes-smart-components (which uses eslint-config-stripes) and found that I was getting new warnings about constructions like:
<Route
path={`${this.props.match.path}/view/:id`}
render={props => <this.connectedNotes
stripes={stripes}
onToggle={this.toggleNotes}
link={`${this.props.moduleName}/${props.match.params.id}`}
{...props}
/>}
/>
Clarity would not be improved by surrounding the `<this.connectedNotes>` invocation with redundant parentheses.
> Disable the rule "react/jsx-wrap-multilines"

- index.js
`console.log()` statements were being allowed by `eslint-config-stripes`, causing tedious follow-up work like https://github.com/folio-org/stripes-core/pull/160#issuecomment-359026041
This won't cause linting to throw an error... yet. I recommend leaving it as a warning for a while to give `folio-org` developers a few months to clean up the warnings that will result. After those are minimized, we can tune this up to error.
> Throw warning for console statements

- index.js
Now that React and ReactDOM have moved to being listed as peer dependencies in all projects (save for stripes-core) we should turn off this error.
> Turn off errors for importing peer dependencies

- index.js
For reference, here are the rules pages:
https://eslint.org/docs/rules/function-paren-newline
https://eslint.org/docs/rules/object-curly-newline
https://eslint.org/docs/rules/prefer-destructuring
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-tag-location.md
Basically, we've got a lot of code that violates these rules and I'm not 100% sold on having them turned on anyway. 
Personally, I actually prefer to write my code following these rules but I _do_ find that having it enforced is slightly paternalistic. If we want to keep them on, I'm all ears.
> Turn off some newline rules

- index.js
Fancy - now we don't have to chuck `.eslintrc` files into all of our `test` directories! 🍾
> Added a section for rule overrides for test files

- package.json
This conforms to the SPDX standard expression of this licence:
https://spdx.org/licenses/Apache-2.0.html
> Change license metadata from "Apache 2.0" to "Apache-2.0"

- package.json
Versions prior to 6.0.3 emit the following warning in stripes-components:
```
/Users/mike/git/folio/stripes/stripes-components/lib/MultiColumnList/MCLRenderer.js
584:11  error  Visible, non-interactive elements with click handlers must have at least one keyboard listener  jsx-a11y/click-events-have-key-events
/Users/mike/git/folio/stripes/stripes-components/lib/NavList/NavList.js
31:9  error  Visible, non-interactive elements with click handlers must have at least one keyboard listener  jsx-a11y/click-events-have-key-events
```
on elements with `role="presentation"`, which should be ignored.
Fixes [STRIPES-511](https://issues.folio.org/browse/STRIPES-511)
> update eslint-plugin-jsx-a11y dep to ^6.0.3

- index.js
Allows either of the two styles:
1. Nesting:
<label>
text
<control />
</label>
2. ID-reference:
<label htmlFor="foo">text</label>
<control id="foo" />
Rather than requiring both nesting _and_ ID-reference:
<label htmlFor="foo">
text
<control id="foo" />
</label>
> Modify jsx-a11y/label-has-for

- index.js
I'm linting this code:
```
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json',
'X-Okapi-Tenant': request.get('X-Okapi-Tenant'),
'X-Okapi-Token': request.get('X-Okapi-Token')
}
```
ESLint, with the present "quote-props" configuration, wants me to remove the quoting around the key "Accept"; but it seems pretty obvious to me that the code is clearer and more consistent if it's quoted in the same way as the other keys in the same object.
> Use "consistent" configuration for the "quote-props" rule

- index.js
Rationale: I am linting this code:
```
{
schema,
context: {
query: request.body,
okapi: {
url: request.get('X-Okapi-Url'),
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json',
'X-Okapi-Tenant': request.get('X-Okapi-Tenant'),
'X-Okapi-Token': request.get('X-Okapi-Token')
}
}
}
}
```
ESLint wants me to put commas on the end of all the last five lines but the very last:
```
'X-Okapi-Token': request.get('X-Okapi-Token'),
},
},
},
}
```
This is simply wrong. No-one ever writes code like that except when they are doing it to satisfy an ESLint rule. The usual rationale for a dangling comma -- that it makes it easier to add and remove individual entries -- is nonsensical in such a situation.
The reconfiguration provided by this pull-request allows but does not require that …
> Reconfigure comma-dangle to use "only-multiline" everywhere

- index.js
Once again, this arises from ESLint's desire to make me rewrite perfectly good code in a way that makes it worse. In this case:
```
`${okapi.url}/users` + (cql ? `?query=${cql}` : '')
```
which it wants me to replace with
```
`${okapi.url}/users{cql ? `?query=${cql}` : ''}`
```
Sometimes templates are a better way to express an idea than concatenation; sometimes concatenation expresses it more cleanly. How can a machine determine which cases fall into each category? It can't -- or, at least, ESLint can't. Programmers can, so we should use those instead.
> Do not prefer template

- index.js
[This rule](https://eslint.org/docs/rules/arrow-parens) seems to be motivated primarily by the extremely unlikely scenario of accidentally typing `if (a => b)` when you mean `if (a >= b)` -- something that I doubt has _ever_ happened. To help avoid this non-issue, it makes all sorts of weird and arbitrary demands about when the parameters to an arrow function should and should not be parenthesised, based on some combination of how many parameters there are and whether the body is an expression to be yielded or a block to be executed.
One irritating thing about this rule is how you end up changing everything when you change anything. I might have a nice simple arrow function
```
foo => (foo * 2)
```
Then I decide I want to see logging:
```
foo => { console.log(`doubling ${foo}`); return …
```
> Turn off the "arrow-parens" rule

- index.js
Much the same arguments as for [turning off `arrow-parens`](https://github.com/folio-org/eslint-config-stripes/pull/24). Under the present regimen, if I have code like:
```
somePromise.then(json => {
console.log('extracting from', json);
return json.users;
});
```
then when I remove the logging, ESLint won't let me just delete the line I no longer need, but tells me to change it to:
```
somePromise.then(json => json.users);
```
I think that's a call for me to make, not a program.
> Turn off "arrow-body-style" rule

- index.js
- Sometimes a renderer or function is appropriate only to a given React component.
- Sometimes that component is class based.
- Sometimes all other functions use `this` so are class methods already.
- Splitting out a single function in those cases looks really ugly and in the future, can lead to unnecessary refactoring and uneasily parsed diffs.
> Turned off class-methods-use-this

- package.json
`eslint-plugin-react` has been making frequent ruleset changes without major version bumps. We want to be more deliberate about rule changes, so we stop getting surprised by changes like this: https://github.com/folio-org/stripes-smart-components/pull/184
Pin `eslint-plugin-react`'s version to prevent future surprise changes. This also includes a major version bump to `eslint-config-stripes`.
> Pin eslint-plugin-react version

- CHANGELOG.md
- index.js
- package.json
This rule complains about perfectly cromulent code such as:
res.push({
base:      jsonSchema['folio:linkBase'],
fromField: jsonSchema['folio:linkFromField'],
toField:   jsonSchema['folio:linkToField'],
include:   jsonSchema['folio:includedElement'],
});
I've looked through all the configuration options described at https://eslint.org/docs/rules/key-spacing and it seems there is no sufficiently flexible way to configure this that will allow all reasonable ways of laying out an object literal. So I think the best thing is just to turn it off.
> Allow any key spacing

- index.js
- package.json
We've got a lot of `// eslint-disable-line` on `import`s of this package and I noticed that doing so has prevented lint from showing other errors about that line.
This will allow us to remove those disables.
> Add an exception for stripes-config in import/no-unresolved

- package.json
`eslint-plugin-jsx-a11y` released a new minor version with rule changes (see https://github.com/folio-org/stripes-components/pull/478#issuecomment-402658404)
To prevent surprise rule changes for FOLIO developers, we can use the same approach we took in https://github.com/folio-org/eslint-config-stripes/pull/30, but this time pin _everything_.
I'll make a follow-up PR that updates all the ruleset dependencies to their latest versions and bumps `eslint-config-stripes` to `3.0.0`.
> Pin all ruleset dependencies

- index.js
- package.json
- [`operator-linebreak`](https://eslint.org/docs/rules/operator-linebreak): completely off (see https://github.com/folio-org/stripes-components/pull/538 for conversation)
- [`lines-between-class-members`](https://eslint.org/docs/rules/lines-between-class-members): modified to make BigTest interactors more readable
> Modify class member and operator linebreak rules

- CHANGELOG.md
- package.json
Follow-up from https://github.com/folio-org/ui-developer/pull/21
`webpack` can be satisfied as a `peerDependency` of `eslint-import-resolver-webpack` by delivering it as a dependency of `eslint-config-stripes`.
This means Stripes UI modules don't have to add `webpack` to `devDependencies`.
Proof-of-concept: https://github.com/folio-org/ui-eholdings/pull/559
> Move webpack to dependencies

- CHANGELOG.md
- index.js
- package.json
Since React 16.8 supports hooks, there are some practices which need to be followed and there are few eslint [rules](https://reactjs.org/docs/hooks-rules.html) for that.
> ESCONF-2: Add eslint rules for react hooks

- CHANGELOG.md
- package.json
- yarn.lock
- Updated all plugins and webpack to match version used in stripes-cli.
- Tested in local workspace with `stripes-util` to ensure that `yarn lint` command still operates properly.
> Bumped eslint version to ^6.2.1

- CHANGELOG.md
- package.json
- yarn.lock
- Fulfills part of [STRIPES-648](https://issues.folio.org/browse/STRIPES-648).
- Bumping version up to 5.0.0 so that consumers must intentionally upgrade their `package.json` dependency version reference.
- Tested in local workspace to ensure references are pulled in correctly.
> Security update eslint to >= 6.2.1 or eslint-util >= 1.4.1

- CHANGELOG.md
- index.js
It does what the label says.
[Here's the rule.](https://eslint.org/docs/rules/quote-props)
Essentially, what it means is that if we want to have an object like
```
const sharedProps = {
'aria-label': 'A label',
id: 'an-id,
foo: 'bar',
}
```
we need to put quotes arounds `id`, `foo`, and any other property names for the sake of consistency with the quoted `aria-label` prop name (which requires them because of the hyphen).
This is silly.
> Turn off quote-props rule

- CHANGELOG.md
- index.js
since they contradict patterns already well-established in our codebases.
Example violation of `react/jsx-props-no-spreading`:
```
render() {
return (
<MyComponent {...this.props} />
);
}
```
Example violation of `react/static-property-placement` (since it resides inside a class):
```
export default class GreetingModal extends React.Component {
static propTypes = {
open: PropTypes.bool,
onClose: PropTypes.func,
};
```
I noticed this first appearing after upgrading `eslint` to 6.2.1.
> Turn off and `react/jsx-props-no-spreading` and `react/static-property-placement` rules

- CHANGELOG.md
- index.js
- package.json
Establish order for `static-variables` to appear after `static-methods` but before everything else to match our current style since it is now acknowledged by https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md.
> Stripes 648

- CHANGELOG.md
- index.js
- package.json
- Ignoring rules that eslint 6 introduced which are accepted practice in FOLIO.
> Global overrides for eslint 6

- CHANGELOG.md
- index.js
This lets us avoid `{' '}` which is just silly. There is simply no way
```
<div>
blah blah 
{' '}
{foo}
</div>
```
is superior to
```
<div>blah blah {foo}</div>
```
> Turn off `react/jsx-one-expression-per-line`

- index.js
Does what it says on the tin.
https://eslint.org/docs/rules/camelcase#allow
> Turn off camelcase for UNSAFE_ methods

- yarn.lock
GitHub reported versions of `minimist`, `acorn`, and `kind-of` from the
previous `yarn.lock` had known security vulnerabilities. Installing
fresh pulls in new releases that are not vulnerable.
> update yarn.lock, receive patched deps

- index.js
ESLint recently started warning us about multiple empty lines. CAN YOU
IMAGINE? The horror. THE HORROR! An additional side-effect of this
warning was world peace, and also the elimination of global hunger,
poverty, and a COVID-19 vaccine. Too bad we'll just have to live without
those things.
> do not complain about multiple empty lines

- CHANGELOG.md
- package.json
Somewhere in a transitive dependency, somebody thought it would be super
cool to use `∞` instead of `Infinity` without correctly updating their
peer-deps. This support wasn't introduced in `eslint-plugin-import`
until at least `v2.22.1`, so we need that.
Refs [STRIPES-711](https://issues.folio.org/browse/STRIPES-711)
> STRIPES-711 update deps to avoid errors

- CHANGELOG.md
- acquisitions.js
to enable import of shared config using stripes workspace (`"extends": ["@folio/eslint-config-stripes/acquisitions"]`)
> add Acquisitions-UI config

- index.js
[I don't really see the point of this rule.](https://eslint.org/docs/rules/no-await-in-loop)
The only times I await in a for-loop is when I expressly want to wait for the first iteration before firing the second iteration. If I didn't care about waiting between iterations, I'd use `forEach` like a sane human being.
> Turned off no-await-in-loop

- CHANGELOG.md
- index.js
- package.json
This PR turns off both `react/jsx-uses-react` and `react/react-in-jsx-scope` in order to comply with the new JSX plugin setup in:
https://github.com/folio-org/stripes-webpack/pull/11
More info:
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint
> STRWEB-5: Turn off jsx-uses-react and react-in-jsx-scope

- CHANGELOG.md
- index.js
This PR is related to the work done in:
https://github.com/folio-org/stripes-webpack/pull/11 and https://github.com/folio-org/eslint-config-stripes/pull/79
After setting it up the error:
`React is defined but never used no-unused-vars`
started showing up everywhere.
React created a tool to clean it up:
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports
But for now we can turn it off here.
> ESCONF-4: Turn off warnings about no-unused-vars for React

- CHANGELOG.md
- index.js
- package.json
Replace `babel-eslint` with `@babel/eslint-parser`, and upgrade many
related dependencies at the same time. `@babel/eslint-parser` needs
access to the babel options (or a link directly to the babel config
file) in order to handle parsing correctly; this is handled here by
importing the config directly from `@folio/stripes-webpack`.
Note: this is a major-version-upgrade due to bumping the eslint peer-dep to v7. It's _possible_ we could get away with supporting v6 or v7 here, but I don't think it's likely a good idea. And since we tend to lock to specific versions of of this module anyway, I don't think changing the major version, rather than the minor, will actually be a significantly different impact.
Refs [ESCONF-8](https://issues.folio.org/browse/ESCONF-8), …
> ESCONF-8 replace babel-eslint with @babel/eslint-parser

- CHANGELOG.md
- package.json
Really, this is ESCONF-8, but when that work was merged we didn't know
the next version of stripes-webpack would be a major version.
Refs [ESCONF-8](https://issues.folio.org/browse/ESCONF-8), [ESCONF-10](https://issues.folio.org/browse/ESCONF-10)
> ESCONF-10 import babel options from stripes-webpack

- CHANGELOG.md
- package.json
Upgrade to `webpack` `v5`. It would be so lovely if there were a way to
provide dev-peer-deps. Alas.
Refs [ESCONF-13](https://issues.folio.org/browse/ESCONF-13), [STRWEB-4](https://issues.folio.org/browse/STRWEB-4)
> ESCONF-13 use webpack v5

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/ESCONF-13
There are 2 corresponding PRs related to this:
* stripes-webpack https://github.com/folio-org/stripes-webpack/pull/36
* stripes-cli https://github.com/folio-org/stripes-cli/pull/270
> ESCONF-13: Upgrade stripes-webpack to v3 and webpack to v5

- CHANGELOG.md
- package.json
Reverts folio-org/eslint-config-stripes#85
Rolling back to webpack v4 due to numerous/so-far-insurmountable BigTest config glitches.
> Revert "ESCONF-13: Upgrade stripes-webpack to v3 and webpack to v5"

- CHANGELOG.md
- package.json
webpack 5 is back, baby, back!
Reverts folio-org/eslint-config-stripes#92
> Revert "revert to webpack v4"

- CHANGELOG.md
- package.json
Recent `webpack` releases interact poorly with `moment` and
`karma-webpack`. While this isn't an issue here directly, the dependency
here does pull `webpack` into the build tree and if this version,
instead of `stripes-cli`'s, gets hoisted, then other modules can be
impacted by the loose constraint here.
Thus, here too we must lock `webpack` to `~5.68.0`. 😞 
Refs [ESCONF-16](https://issues.folio.org/browse/ESCONF-16), [STCLI-195](https://issues.folio.org/browse/STCLI-195)
> ESCONF-16 lock webpack to ~5.68.0

- CHANGELOG.md
- package.json
Bump `@folio/stripes-webpack` to `v4` to stay in sync with the version
provided by `@folio/stripes-cli`. This makes me feel
`@folio/stripes-webpack` ought to be a peer, rather than a direct dep,
but I think that would only work in NPM (where peers are installed)
but not in yarn (where peers are ignored). Hmmmmmm.
Refs [ESCONF-18](https://issues.folio.org/browse/ESCONF-18), [STCLI-203](https://issues.folio.org/browse/STCLI-203)
> ESCONF-18 bump stripes-webpack to v4

- CHANGELOG.md
- package.json
Update plugins to current versions to pickup features and bug-fixes,
e.g. recognizing state values in gDSFP as in-use.
The only major change here is to `no-only-tests` which has changed the
way block-scope matching works. We don't configure block-scope matching
so this is a non-issue for us.
Refs [ESCONF-21](https://issues.folio.org/browse/ESCONF-21)
> ESCONF-21 update eslint-plugin versions

- index.js
- package.json
This PR adds linting rules for TypeScript.  This includes adding the TypeScript parser and eslint plugin to the dependencies, as this allows eslint to properly parse and understand TypeScript files.  Additionally, all recommended linting rules are added, such as `noExplicitAny`, disallowing the dangerous `any` wildcard type, among [many other rules](https://typescript-eslint.io/rules/).  There may be merit in some of the "strict" rules listed on that page, however, the recommended should be more than enough for 99% of cases, and the others are fairly opinionated.
For `.d.ts` files, which TypeScript uses as supplemental declaration-only files (cannot contain any real code), I had to disable the `react/no-unused-prop-types` flag.  Since these files contained stubbed declarations such as: …
> ESCONF-19: Add TypeScript linting

- CHANGELOG.md
- index.js
Loosen rules about tests:
* we don't care about proptypes in mocks
* we don't care if a mock provides a single, non-default export
Loosen rules about what files are recognized as tests:
* they may be in /test
* they may be nested in /src/*/tests/
* they may be named *.test.js
Refs [ESCONF-20](https://issues.folio.org/browse/ESCONF-20)
> ESCONF-20 loosen rules about tests

- CHANGELOG.md
- package.json
Platform complete and individual modules are currently failing with:
https://jenkins-aws.indexdata.com/job/Automation/job/build-platform-complete-snapshot/13912/consoleText
This is due to the issue with `enhanced-resolve v5.11.0` (thank you @zburke for pointing to it):
https://github.com/webpack/enhanced-resolve/issues/362
This PR locks `enhanced-resolve` to `"~5.10.0"` 
Fixes [ESCONF-26](https://issues.folio.org/browse/ESCONF-26)
> ESCONF-26: Avoid enhanced-resolve ~5.11.0 due to incompatibilities with webpack-virtual-config

- package.json
https://issues.folio.org/browse/ESCONF-27
This PR reverts the changes from https://github.com/folio-org/eslint-config-stripes/pull/107 since this was fixed directly in webpack: https://github.com/webpack/enhanced-resolve/pull/364
> ESCONF-27: Remove enhanced-resolve resolutions entry

- CHANGELOG.md
- package.json
Lock `stripes-webpack` to `~4.1.x`, the same version that will be used by `stripes-cli` `2.6.x`, in order to avoid pulling multiple different versions from being pulled into the bundle.
Refs [ESCONF-30](https://issues.folio.org/browse/ESCONF-30)
> ESCONF-30 lock stripes-webpack to ~4.1

- package.json
Adding `eslint-config-stripes` to a repository should be an atomic action, i.e. `eslint-config-stripes` should be self-contained and not require adding any additional dev-deps. This will allow related dependencies to be managed in a single place, reducing maintenance overhead from every repository to a single repository.
Refs [ESCONF-29](https://issues.folio.org/browse/ESCONF-29)
> ESCONF-29 directly satisfy all lint-related deps

- CHANGELOG.md
- package.json
We pinned webpack in [STCLI-195](https://issues.folio.org/browse/STCLI-195) but the build errors we encountered at that time have abated. 
Refs [ESCONF-28](https://issues.folio.org/browse/ESCONF-28)
> ESCONF-28 unpin webpack dependency

- CHANGELOG.md
- package.json
*BREAKING* Bump `@folio/stripes-webpack` to v5. This is a breaking change even though `@folio/stripes-webpack` is a direct dependency because what we really need is for the version to be consistent _in dev deps_, which is sorta like a peer-dev-dep, but there is no such thing.
Refs [ESCONF-32](https://issues.folio.org/browse/ESCONF-32)
> ESCONF-32 update @folio/stripes-webpack to v5

- package.json
As part of [Jira STRIPES-900](https://issues.folio.org/browse/STRIPES-900), all modules should use one `typescript` version, inherited from `@folio/stripes-webpack`.  Therefore, the explicit `typescript` version in this `package.json` should be removed.
> [ESCONF-38] Remove explicit typescript version

- CHANGELOG.md
- index.js
Turn off `import/prefer-default-export` since named export provides many advantages one of them is to have the same name in different files.
[ESCONF-42](https://folio-org.atlassian.net/browse/ESCONF-42)
> ESCONF-42: Turn off `import/prefer-default-export`.

- .github/workflows/ui.yml
We don't have an MD, so we better tell the workflow not to try to publish one.
> do not publish non-existent module descriptor

- CHANGELOG.md
- index.js
`prop-types` will be removed in React v19; there is no value in forcing people to maintain something that we know is about to be ignored.
Refs [ESCONF-49](https://folio-org.atlassian.net/browse/ESCONF-49)
> ESCONF-49 turn off react/prop-types warnings

- .github/workflows/ui.yml
- CHANGELOG.md
Provide `^1.0.0` compatibility.
Refs [ESCONF-50](https://folio-org.atlassian.net/browse/ESCONF-50)
> ESCONF-50 loosen GA workflow constraint

- CHANGELOG.md
- index.js
FormattedNumber expects string values in its `style` prop, but ESLint expects `style` to always correspond to an object for spreading CSS attributes onto the DOM. Whoops; that's [ESLint's mistake, not react-intl's](https://github.com/formatjs/formatjs/issues/833).
Refs [ESCONF-52](https://folio-org.atlassian.net/browse/ESCONF-52)
> ESCONF-52 permit string values in <FormattedNumber style>
